# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dbd033b9e646a6103b988fbb3a59cdfd0fd9913ed566948b4db14aa3da68266024f03112e5dc36dcdf0919bf0c040c44664907663cc1a4d210ab147a574199ca

test:
  secret_key_base: 12bad0508c4b8a89bceb8471fa9af46c952012a36ba9b50442d528b163ecf45353f3f3f8f801be560c05c4b89509775d202fc288c3635f2738845c95711f37e3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
